# application/uow.py
from typing import Protocol
from app.application.repositories.user_repository import UserRepository


class UnitOfWork(Protocol):
    users: UserRepository

    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc, tb): ...
    async def commit(self): ...
    async def rollback(self): ...
