# application/uow.py
from typing import Protocol, Self
from app.application.repositories.user_repository import UserRepository


class UnitOfWork(Protocol):
    users: UserRepository

    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
